### ISSUE TITLE
Please change license back to LGPL

### ISSUE THREAD

**Issue by krogank9** [kbengine/kbengine#607]
Hi, I request that you change license back. I worked for a couple months on free plugins and documentation for the engine when I thought it would be LGPL3. Then you changed it suddenly without warning.

The new license isn't clear, and sounds restrictive. It's your engine so you can change license, but we can fork all previous code already released under LGPL3. I want to continue contributing, so why not change it back and we can work together?

You can still make money on LGPL3, just charge for technical support. In fact, I will donate $100 USD in good faith if you change it back.

**Comment by kebiao** [comment]
Hi,
I'm very sorry, but we have actually made announcements in the Chinese community. Since we have already obtained investment, we have already set up a company. For the benefit of the company in the future, we have to make some restrictions. The current limit is similar to UE4.

This is the current official website:
https://www.comblockengine.com/

This is no longer my decision. I can do nothing about it.

You can indeed fork an LGPL version and then maintain your own version.
https://github.com/kbengine/kbengine/tree/1.x

**Comment by krogank9** [comment]
It's ok. I am translating source comments to English to learn the engine and work on my own fork. I wish you best of luck.

Thank you for your help.

**Comment by krogank9** [comment]
Was LGPL3 here? https://github.com/krogank9/kbengine/commit/893872250a600b4771951b76fe44962d4963bb65

It's when I forked, and all files still say LGPL3. I don't want any copyright problems.

**Comment by kebiao** [comment]
Yes, we will remember your contribution and thank you very much.
If you have questions you can still ask me.

**Comment by krogank9** [comment]
Thank you KBE

**Comment by duong2179** [comment]
Hi there, does this mean KBE is NOT open for free use anymore?
